import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import PopUpButton from "~/components/PopUpButton";
import PostView from "~/components/PostView";
import { api } from "~/utils/api";
import Nav from "../components/Nav";

const Home: NextPage = () => {
  const user = useUser();
  const { data } = api.posts.getAll.useQuery();
  // console.log("user: ", user?.user?.id);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative h-screen">
        <Nav />

        <div className="relative flex h-full w-full flex-col bg-emerald-50 p-4 md:flex-row lg:px-20 lg:py-6">
          {data?.map((fullPost) => {
            return <PostView {...fullPost} key={fullPost.post.id} />;
          })}
        </div>

        <PopUpButton />
      </main>
    </>
  );
};

export default Home;
