import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import RequestCard from "../components/RequestCard";
import Nav from "../components/Nav";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();
  const { data } = api.posts.getAll.useQuery();

  console.log("user: ", user);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative h-screen">
        <Nav />

        <div className="relative z-[-1] flex h-full w-full flex-col bg-emerald-50 p-4 md:flex-row lg:px-20 lg:py-6">
          {data?.map((post) => {
            return <RequestCard key={post.id} content={post.content} />;
          })}
        </div>
      </main>
    </>
  );
};

export default Home;
